spring.datasource.url=jdbc:h2:file:${user.home}/GestioEPIs/data/gestio_epis
spring.flyway.url=jdbc:h2:file:${user.home}/GestioEPIs/data/gestio_epis
app.storage.location=${user.home}/GestioEPIs/uploads

spring.jpa.show-sql=false

logging.file.name=${user.home}/GestioEPIs/logs/app.log
logging.logback.rollingpolicy.max-file-size=5MB
logging.logback.rollingpolicy.max-history=5
logging.logback.rollingpolicy.total-size-cap=20MB
