CREATE TABLE person (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(255)
);

CREATE TABLE category (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255)
);

CREATE TABLE location (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255),
                          description VARCHAR(255)
);

CREATE TABLE purchase_order (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                name VARCHAR(255),
                                comments VARCHAR(255),
                                order_date DATE,
                                file_path VARCHAR(255)
);

CREATE TABLE delivery_note (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               delivery_date DATE,
                               file_path VARCHAR(255),
                               purchase_order_id BIGINT REFERENCES purchase_order(id)
);

CREATE TABLE handover (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          handover_date DATE,
                          person_id BIGINT REFERENCES person(id)
);

CREATE TABLE clothing_item (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               subcategory VARCHAR(255),
                               price DOUBLE PRECISION NOT NULL,
                               item_size VARCHAR(255),
                               brand VARCHAR(255),
                               code VARCHAR(255),
                               category_id BIGINT REFERENCES category(id),
                               location_id BIGINT REFERENCES location(id),
                               purchase_order_id BIGINT REFERENCES purchase_order(id),
                               delivery_note_id BIGINT REFERENCES delivery_note(id),
                               handover_id BIGINT REFERENCES handover(id)
);