CREATE TABLE subcategory (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             name VARCHAR(255),
                             category_id BIGINT REFERENCES category(id)
);

ALTER TABLE clothing_item ADD COLUMN subcategory_id BIGINT REFERENCES subcategory(id);

-- Migra qualsevol subcategoria de text lliure ja existent a la nova taula
INSERT INTO subcategory (name, category_id)
SELECT DISTINCT subcategory, category_id
FROM clothing_item
WHERE subcategory IS NOT NULL AND category_id IS NOT NULL;

UPDATE clothing_item
SET subcategory_id = (
    SELECT s.id FROM subcategory s
    WHERE s.name = clothing_item.subcategory
      AND s.category_id = clothing_item.category_id
)
WHERE subcategory IS NOT NULL AND category_id IS NOT NULL;

ALTER TABLE clothing_item DROP COLUMN subcategory;
